name: Context
on: push

jobs:
  context-ouput:
    runs-on: ubuntu-16.04
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure() # this runs if the prev job fails
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always() # this will always run
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: functions
        run: |
          echo ${{ contains('hello', 'll')}}
          echo ${{ startsWith('hello', 'he')}}
          echo ${{ endsWith('hello', 'lo')}}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!')}}
  continue-on-error-example:
    runs-on: ubuntu-latest
    steps:
      - name: Demonstrate continue on error
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: ech0o "$GITHUB_CONTEXT"
        continue-on-error: true # by default its false
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"